"""Machine-testable v0.3.0-dev contracts."""

from nana_sidecar.contracts.authorization import (
    ActionHashMaterial,
    AuthorizationMatch,
    GrantMatchContext,
)
from nana_sidecar.contracts.catalog import ContractCatalogSchema
from nana_sidecar.contracts.commands import Command
from nana_sidecar.contracts.domain import (
    Action,
    ActionReceipt,
    Approval,
    Artifact,
    ArtifactCommittedEvent,
    ArtifactLifecycleEvent,
    ArtifactReconciledEvent,
    ArtifactStagedEvent,
    Evidence,
    Event,
    Finding,
    Hypothesis,
    Inquiry,
    Locator,
    Method,
    Plan,
    PolicyGrant,
    Project,
    Relation,
    Resource,
    Run,
    Decision,
    Workspace,
)

__all__ = [
    "Action",
    "ActionHashMaterial",
    "ActionReceipt",
    "Approval",
    "Artifact",
    "ArtifactCommittedEvent",
    "ArtifactLifecycleEvent",
    "ArtifactReconciledEvent",
    "ArtifactStagedEvent",
    "AuthorizationMatch",
    "Command",
    "ContractCatalogSchema",
    "Decision",
    "Evidence",
    "Event",
    "Finding",
    "GrantMatchContext",
    "Hypothesis",
    "Inquiry",
    "Locator",
    "Method",
    "Plan",
    "PolicyGrant",
    "Project",
    "Relation",
    "Resource",
    "Run",
    "Workspace",
]
